name: discotech
favicon: null
layout_spectrum: 0.6358162104152143
typography_spectrum: 0.23019637283869088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5139311086386442
  lightness: 0.851538750808686
  saturation: 0.18719494831748307
  rhythmicContrast: 0.8484636945649981
purpose: []
